=== JonTheisNilsson/CYBS_01_PRO_EXAM/json_schema/schema_alert.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "alertId": {"type": "string"},
    "category": {"type": "string"},
    "computerDnsName": {"type": "string"},
    "detectionSource": {"type": "string"},
    "entities": {
      "type": "object",
      "properties": {
        "domains": {
          "type": "array",
          "items": [{"type": "string"}]
        },
        "emails": {
          "type": "array",
          "items": [{"type": "string"}]
        },
        "fileHashes": {
          "type": "array",
          "items": [{"type": "string"}]
        },
        "ips": {
          "type": "array",
          "items": [{"type": "string"}]
        },
        "processes": {
          "type": "array",
          "items": [{"type": "string"}]
        },
        "urls": {
          "type": "array",
          "items": [{"type": "string"}]
        }
      },
      "required": [
        "domains",
        "emails",
        "fileHashes",
        "ips",
        "processes",
        "urls"
      ]
    },
    "firstActivity": {"type": "string"},
    "lastActivity": {"type": "string"},
    "machineId": {"type": "string"},
    "severity": {"type": "string"},
    "title": {"type": "string"}
  },
  "required": [
    "alertId",
    "category",
    "computerDnsName",
    "detectionSource",
    "entities",
    "firstActivity",
    "lastActivity",
    "machineId",
    "severity",
    "title"
  ]
}

=== JonTheisNilsson/CYBS_01_PRO_EXAM/json_schema/response_example_alert.json
{
    "alertId": "ALT-SQLI-001-0",
    "category": "Exploitation",
    "computerDnsName": "CAD01-TCORP.oresund-industrial.dk",
    "detectionSource": "Microsoft Defender for Endpoint",
    "entities": {
        "domains": [
            "update-oresund.com"
        ],
        "emails": [
            "eng.larsen@oresund-industrial.dk"
        ],
        "fileHashes": [
            "5d41402abc4b2a76b9719d911017c592"
        ],
        "ips": [
            "192.168.30.10",
            "172.16.100.10"
        ],
        "processes": [
            "python3.exe sqlmap.py -u http://172.16.100.10/portal/login --data \"username=admin&password=test\" --technique=B --level=5 --batch",
            "python3.exe sqlmap.py -u http://172.16.100.10/portal/login --data \"username=admin' OR '1'='1'-- -&password=x\" --dump --tables"
        ],
        "urls": [
            "http://172.16.100.10/portal/login?username=admin' OR '1'='1'-- -&password=x",
            "http://172.16.100.10/portal/login?username=admin'--&password="
        ]
    },
    "firstActivity": "2026-04-29T03:47:02.095331+00:00",
    "lastActivity": "2026-04-29T05:07:02.095331+00:00",
    "machineId": "CAD01-TCORP",
    "severity": "High",
    "title": "SQL injection tool (sqlmap) execution detected on CAD01-TCORP"
}
