=== JonTheisNilsson/CYBS_01_PRO_EXAM/json_schema/schema_summary.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "by_classification": {
      "type": "object",
      "properties": {
        "FalsePositive": {"type": "number"},
        "InformationalExpectedActivity": {"type": "number"},
        "TruePositive": {"type": "number" }
      },
      "required": [
        "FalsePositive",
        "InformationalExpectedActivity",
        "TruePositive"
      ]
    },
    "by_severity": {
      "type": "object",
      "properties": {
        "Critical": { "type": "number" },
        "High": { "type": "number" },
        "Low": { "type": "number" },
        "Medium": { "type": "number" }
      },
      "required": [
        "Critical",
        "High",
        "Low",
        "Medium"
      ]
    },
    "by_status": {
      "type": "object",
      "properties": {
        "Active": {"type": "number" },
        "InProgress": {"type": "number" },
        "Resolved": {"type": "number" }
      },
      "required": [
        "Active",
        "InProgress",
        "Resolved"
      ]
    },
    "recent_incidents": { "type": "number" },
    "top_malware_families": { "type": "object" },
    "top_threat_actors": { "type": "object" },
    "total_incidents": { "type": "number" }
  },
  "required": [
    "by_classification",
    "by_severity",
    "by_status",
    "recent_incidents",
    "top_malware_families",
    "top_threat_actors",
    "total_incidents"
  ]
}

=== JonTheisNilsson/CYBS_01_PRO_EXAM/summary_respones.json
{
    "by_classification": {
        "FalsePositive": 204,
        "InformationalExpectedActivity": 191,
        "TruePositive": 196
    },
    "by_severity": {
        "Critical": 159,
        "High": 149,
        "Low": 135,
        "Medium": 148
    },
    "by_status": {
        "Active": 193,
        "InProgress": 201,
        "Resolved": 197
    },
    "recent_incidents": 591,
    "top_malware_families": {
        "BlackEnergy": 58,
        "Cobalt Strike": 70,
        "Emotet": 62,
        "Industroyer": 71,
        "Mimikatz": 61,
        "PowerShell Empire": 64,
        "Qakbot": 70,
        "TRITON": 71,
        "TrickBot": 64
    },
    "top_threat_actors": {
        "APT28": 67,
        "APT33": 68,
        "Lazarus Group": 60
    },
    "total_incidents": 591
}
